# Generated by Django 2.2.5 on 2020-06-09 21:32

from django.db import migrations, models
import django_resized.forms
import predict.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 300], storage=predict.models.OverwriteStorage(), upload_to='uploaded_images/')),
            ],
        ),
    ]
